FROM k8s-base-ww

RUN dnf update -y

RUN dnf install -y haproxy keepalived

#RUN sysctl -w net.ipv4.ip_nonlocal_bind="1" && sysctl -w net.ipv4.ip_forward="1"

COPY keepalived.conf /etc/keepalived/keepalived.conf

COPY check_apiserver.sh /etc/keepalived/check_apiserver.sh

COPY haproxy.cfg /etc/haproxy/haproxy.cfg

