FROM k8s-base-ww

RUN dnf update -y

RUN dnf install -y haproxy keepalived

COPY keepalived.conf /etc/keepalived/keepalived.conf

COPY check_apiserver.sh /etc/keepalived/check_apiserver.sh

COPY haproxy.cfg /etc/haproxy/haproxy.cfg

